/*Q1. What is the total revenue generated by male vs. female customers?*/

select gender,SUM(purchase_amount) as total_revenue
from customer_purchase
group by gender;

/*Q2. Which customers used a discount but still spent more than the average purchase amount? */

select customer_id, purchase_amount
from customer_purchase
where discount_applied='yes' and purchase_amount>=(select AVG(purchase_amount) from customer_purchase)
order by customer_id asc;

/*Q3. Which are the top 5 products with the highest average review rating?*/

select top 5 item_purchased,round(avg(review_rating),2) as avg_rating
from customer_purchase group by item_purchased
order by avg_rating desc;

/*Q4. Compare the average Purchase Amounts between Standard and Express Shipping. */
select shipping_type,AVG(purchase_amount) as avg_amount
from customer_purchase
group by shipping_type having shipping_type in ('Standard' ,'Express');

/*Q5. Do subscribed customers spend more? Com	pare average spend and total revenue 
between subscribers and non-subscribers */

select subscription_status,COUNT(customer_id) AS total_customers,sum(purchase_amount) as total_spent,AVG(purchase_amount) as avg_spent
from customer_purchase
group by subscription_status;

/*Q6. Which 5 products have the highest percentage of purchases with discounts applied?*/

select top 5 item_purchased,ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer_purchase
GROUP BY item_purchased
ORDER BY discount_rate DESC;

/*Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.*/

with customer_segment_ as
(
select customer_id, previous_purchases,
	case when previous_purchases=1 then 'New'
		 when previous_purchases between 2 and 10 then 'Returning'
		 else 'Loyal' end as customer_segment
from customer_purchase
)
select customer_segment,count(*) as count_
from customer_segment_
group by customer_segment
order by count_ asc;

/*Q8. What are the top 3 most purchased products within each category? */

with most_purchased as 
(
	select category,item_purchased, count(*) as no_of_item_purchased
	,ROW_NUMBER() over(partition by category order by count(*) desc) as ranking
	from customer_purchase
	group by category, item_purchased
)
select  *
from most_purchased
where ranking<=3;

/*Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?*/

select subscription_status,  COUNT(customer_id) AS repeat_buyers
from customer_purchase
where previous_purchases>5 
group by subscription_status;

/*Q10. What is the revenue contribution of each age group? */

select age_group, sum(purchase_amount) as revenue_contribution
from customer_purchase
group by  age_group
order by revenue_contribution desc;



